apply-crd:
	kubectl apply -f deploy/crds/serving.octohelm.tech_qservices_crd.yaml

apply-example:
	kubectl apply --filename ./deploy/examples/service.yaml

delete:
	kubectl delete -f deploy

apply:
	kubectl apply -f deploy

test.apply: apply
	kubectl apply --filename ./deploy/examples/service.yaml
	kubectl get deployments -n default | grep srv-test

test.delete:
	kubectl delete --filename ./deploy/examples/service.yaml
	kubectl get deployments -n default | grep srv-test