kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: istio-operator
          image: "{{ .Values.image.hub }}/qservice-operator:{{ .Values.image.tag }}"
          args:
            - --enable-leader-election
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: INGRESS_GATEWAYS
              value: "{{ .Values.ingressGateways }}"