apiVersion: "serving.octohelm.tech/v1alpha1"
kind: "QService"
metadata:
  name: "srv-test"
  namespace: "default"
  annotations:
    serving.octohelm.tech/imagePullSecret: "docker-hub://pull-only:123123@docker.io/"
    autoscaling.octohelm.tech/minScale: "1"
    autoscaling.octohelm.tech/maxScale: "5"
    autoscaling.octohelm.tech/metrics: Resource(name = cpu, targetAverageUtilization = 70)
  labels:
    app: "srv-test"
    group: "default"
spec:
  replicas: 2
  image: "nginx:alpine"
  ports:
    - "80"
  envs:
    Pg_Endpoint: postgresql://pg:pg@172.16.0.77:5432/idp
  resources:
    cpu: 500/2000m
