namespace: qservice-operator

generatorOptions:
  disableNameSuffixHash: true

resources:
  - operator.yaml
  - role.yaml
  - role_binding.yaml
  - service_account.yaml

images:
  - name: qservice-operator
    newName: hub-dev.demo.querycap.com/octohelm/qservice-operator
    newTag: 0.7.4