apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: qservice-operator
  name: qservice-operator
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
  - verbs:
      - '*'
    nonResourceURLs:
      - '*'