name: build

on:
  push:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@master
      - uses: docker/setup-buildx-action@master
      - name: docker login
        run: |
          cat > ~/.docker/config.json << EOF
          ${{ secrets.DOCKER_CONFIG }}
          EOF
      - run: make build.dockerx