name: build

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - uses: docker/login-action@v1
        name: Login ghcr.io
        with:
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
      - uses: docker/login-action@v1
        name: Login docker.io
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
      - id: prepare
        name: prepare
        run: |-
          export TAG=${{ github.sha }}
          if [[ ${{ github.ref }} == "refs/heads/"* ]]; then
            export TAG=$(echo ${{ github.ref }} | sed -e "s/refs\/heads\///")
          fi
          if [[ ${{ github.ref }} == "refs/tags/v"* ]]; then
            export TAG=$(echo ${{ github.ref }} | sed -e "s/refs\/tags\/v//")
          fi
          make prepare
      - uses: docker/build-push-action@v2
        name: Push
        with:
          build-args: ${{ steps.prepare.outputs.build_args }}
          context: .
          file: hack/Dockerfile
          labels: |-
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |-
            ghcr.io/octohelm/${{ steps.prepare.outputs.image }}
            docker.io/octohelm/${{ steps.prepare.outputs.image }}